config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    post "/graphql", to: "graphql#execute"
    post "/login", to: "sessions#login"
    post "/signup", to: "sessions#signup"
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :action_items, only: [:index, :create, :new, :destroy]
    resources :users, only: [:index]
  end

  if Rails.env.development?
    # For testing graphql endpoints in development
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

end

app/models/action_item.rb
class ActionItem < ApplicationRecord
  belongs_to :category
  validates :category, presence: true

  has_many :algorithms, inverse_of: :action_item
  accepts_nested_attributes_for :algorithms
  validate :unique_algorithm_group

  validates :description, presence: true

  scope :by_category, -> (category_name) {
    joins(:category).where(categories: {name: category_name})
  }

  def unique_algorithm_group
    if duplicate_algorithm_groups?
      error_msg = "Can't have more than one algorithm within a certain group."
      errors.add(:algorithms, error_msg)
    end
  end

  private

  def algorithm_group_counts
    # Association proxy methods do not work here on 1st validation,
      # b/c it's before algorithms have saved to database
    self.algorithms
      .group_by { |obj| obj[:group] }
      .map { |k, v| [k,v.count] }
      .to_h rescue {}
  end

  def duplicate_algorithm_groups?
    algorithm_group_counts.any? {|k,v| v > 1 }
  end

end

app/controllers/admin/action_items_controller.rb
class Admin::ActionItemsController < Admin::BaseController
  def index
    @action_items = ActionItem.all
  end

  def create
    category = Category.find(params[:category])
    action_item = category.action_items.new(action_item_params)
    if action_item.save
      flash[:notice] = "Action successfully created!"
      redirect_to admin_action_items_path#(action_item.id)
    else
      flash[:alert] = action_item.errors.full_messages.join(", ")
      redirect_to new_admin_action_item_path
    end
  end

  def new
    @action_item = ActionItem.new
    @categories = Category.all
    @action_item.algorithms.build
  end

  def destroy
    action_item = ActionItem.find(params[:id])
    action_item.destroy!
    flash[:notice] = "Action deleted successfully"
    redirect_to admin_action_items_path
  end

  private

  def action_item_params
    params.require(:action_item).permit(:id, :description, algorithms_attributes: [:id, :formula, :group])
  end

end

app/views/admin/action_items/_algorithm_fields.html.erb
<%= f.fields_for :algorithms do |algorithm_fields| %>
  <div class="col s12">
    <%= algorithm_fields.label :formula %><br>
    <%= algorithm_fields.text_field :formula %><br>
  </div>
  <div class="col s12">
    <%= algorithm_fields.label :group %><br>
    <%= algorithm_fields.select :group, Algorithm.groups.keys %>
  </div>

<% end %>

app/views/admin/action_items/index.html.erb
<div class="row">
  <h1>All Actions</h1>

  <%= link_to "Add new action", new_admin_action_item_path %><br>

<div class="col s12">
  <div id="admin-actions">
    <ul>
      <% @action_items.each do |action_item| %>
        <div class="col s12">
          <div class="col s1"><%= link_to 'X', admin_action_item_path(action_item.id), method: :delete %></div>
          <div class="col s7"><%= action_item.description %></div>
          <div class="col s4"><%= action_item.category.name %></div>
        </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/action_items/new.html.erb
<div class="row">
  <h1>Create New Action</h1>

  <%= form_for [:admin, @action_item] do |f| %>
    <div class="col s12">
      <%= f.label :description %><br>
      <%= f.text_area :description, required: true %><br>
    </div>
    <div id="action-item-algorithms" class="algorithms">
      <%= render 'algorithm_fields', f: f %>
    </div>
    <p><%= link_to_add_fields "Add Algorithm", f, :algorithms, {class: 'btn small', id: 'add-algorithm-btn'} %></p>
    <div class="col s12">
      Category
      <div id="category-items">
        <% @categories.each do |category| %>
          <div>
            <%= radio_button_tag :category, category.id, required: true %>
            <%= label_tag "category_#{category.id}", category.name %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col s12">
    <%= f.submit "Create action", class:"btn right" %>
    </div>
  <% end %>
</div>