config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    post "/graphql", to: "graphql#execute"
    post "/login", to: "sessions#login"
    post "/signup", to: "sessions#signup"
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :action_items, only: [:index, :create, :new, :destroy]
    resources :users, only: [:index]
  end

  if Rails.env.development?
    # For testing graphql endpoints in development
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

end

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "home", root_path %>
    <ul id="nav-mobile" class="right">
      <% if current_user && current_user.admin? %>
        <li><%= link_to 'dashboard', admin_root_path %></li>
      <% end %>
      <% if current_user %>
        <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "sign in", new_user_session_path %></li>
        <li><%= link_to "sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthTemplate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/nav' %>
  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>